### ISSUE TITLE
What should my ASG lifecyclehook look like?

### ISSUE THREAD

**Issue by clayvan** [VirtusLab/kubedrainer#3]
I feel like I'm missing something.

I've deployed the daemonset and IAM roles, but without the ASG lifecycle hook, the daemonset won't be triggered right?

So what should my lifecycle hook/action look like?

Granted I'm new to lifecycle hooks, but I feel like that's the critical part I'm missing.

Thanks in advance! @pawelprazak

**Comment by pawelprazak** [comment]
In CloudFormation it would look like this (assuming your CF resource for ASG is named `NodeGroup`):
```yaml
  NodeGroupLifecycleHook: # for node drainer
    Type: AWS::AutoScaling::LifecycleHook
    Properties:
      AutoScalingGroupName:
        Ref: NodeGroup
      LifecycleTransition: "autoscaling:EC2_INSTANCE_TERMINATING"
      HeartbeatTimeout: 360
```
